name: 'Check branch names for pull requests'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check_branch_names:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1